apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: octolamp-agent-controller-role-binding
subjects:
- kind: ServiceAccount
  name: octolamp-service-account
  namespace: octolamp-system
roleRef:
  kind: ClusterRole
  name: octolamp-agent-controller-role
  apiGroup: rbac.authorization.k8s.io