---
# Source: octolamp/templates/controller-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: octolamp-system
---
# Source: octolamp/templates/controller-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: octolamp-system
  name: octolamp-service-account
---
# Source: octolamp/templates/crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  namespace: octolamp-system
  name: agents.azdo.octolamp.nl
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: azdo.octolamp.nl
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                prefix:
                  type: string
                imagePullSecretName:
                  type: string
              required: [image]
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: agents
    # singular name to be used as an alias on the CLI and for display
    singular: agent
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: AgentSpec
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ag
---
# Source: octolamp/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: octolamp-controller
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - configmaps
      - configmaps/finalizers
      - secrets
      - secrets/finalizers
      - pods
      - pods/logs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - azdo.octolamp.nl
    resources:
      - agents
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
# Source: octolamp/templates/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: octolamp-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: octolamp-controller
subjects:
- kind: ServiceAccount
  name: octolamp-service-account
  namespace: octolamp-system
