apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.package.controllerName }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - configmaps
      - configmaps/finalizers
      - secrets
      - secrets/finalizers
      - pods
      - pods/logs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - {{ .Values.package.crdGroupName }}
    resources:
      - agents
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete